module.exports = {
  apps: [
    {
      name: 'campaign-lottery-api',
      cwd: '/home/ubuntu/campaign-lottery-next/backend-server',
      script: 'node_modules/.bin/next',
      args: 'start --port 18100',
      env: {
        NODE_ENV: 'production',
        PORT: '18100',
        ADMIN_USER: 'admin',
        ADMIN_PASSWORD: 'change-me',
        CORS_ALLOW_ORIGIN: '*',
        MYSQL_ENABLED: 'true',
        MYSQL_HOST: '127.0.0.1',
        MYSQL_PORT: '3306',
        MYSQL_DATABASE: 'campaign_lottery_platform',
        MYSQL_USER: 'campaign_lottery_app',
        MYSQL_PASSWORD: 'change-me',
        MYSQL_CONNECTION_LIMIT: '10',
        REDIS_ENABLED: 'false',
      },
      max_memory_restart: '500M',
      error_file: '/home/ubuntu/.pm2/logs/campaign-lottery-api-error.log',
      out_file: '/home/ubuntu/.pm2/logs/campaign-lottery-api-out.log',
    },
    {
      name: 'campaign-lottery-front',
      cwd: '/home/ubuntu/campaign-lottery-next/front-page',
      script: 'node_modules/.bin/next',
      args: 'start --port 3000',
      env: {
        NODE_ENV: 'production',
        PORT: '3000',
        NEXT_PUBLIC_API_BASE_URL: '',
      },
      max_memory_restart: '500M',
      error_file: '/home/ubuntu/.pm2/logs/campaign-lottery-front-error.log',
      out_file: '/home/ubuntu/.pm2/logs/campaign-lottery-front-out.log',
    },
  ],
};